### PR TITLE
Initial repo structure

### PR DESCRIPTION
**Pull request by adsharma**

### CODE REVIEW

**Comment by kelvich** [comment]
Hm, I thought we agreed on top level repo beeing cargo workspace and only include postgres as a submodule

**Comment by adsharma** [comment]
Yes - that is still the idea. I was thinking that we could add a `Cargo.toml` file at the top level in a subsequent commit.

**Comment by adsharma** [comment]
You can either clone the pull request or browse around here:

https://github.com/adsharma/zenith

vendor/postgres is a submodule.

```
$ git submodule status
 e8790f4e62ab2d527ae89c0d4ad0582a17ae6876 cli (heads/main)
 46a7e72aad214c64f588d0430a3c2472ce95706d consensus (heads/main)
 bad55d4e1610e72e607e8f854c12063b8f51c37e pageserver (heads/main)
 ab596105b55f1d7fbd5a66b66f65227d210b047d vendor/postgres (heads/master) <--- I think you're asking about this
 3e1d859f7f185f5b3978215b1c007d7d61af0874 walkeeper (heads/main)
```

The postgres repo submodule tracks the zenith branch, which is currently the same as master.

**Comment by adsharma** [comment]
Re: shared code between pageserver and walkeeper
 
 You can decide which repo to put it in and then refer to the shared module via a relative path in Cargo.toml of the other module.
 Modules could be structured like:
 
 ```
 wal
├── lib.rs
├── waldecoder.rs
├── walreceiver.rs
└── walredo.rs
```

**Pull request merged**
